
const STORAGE_KEY = 'yueGardenDiary.v3';
const LANG_KEY = 'yueGardenDiary.lang';
const today = new Date();
const iso = d => d.toISOString().slice(0,10);
const daysSince = date => date ? Math.floor((today - new Date(date+'T00:00:00'))/86400000) : 999;
let lang = localStorage.getItem(LANG_KEY) || 'zh';
const state = loadState();
let selectedGroup = '全部';

const I18N = {
  zh:{export:'导出备份',tab_today:'今日',tab_plants:'植物',tab_map:'地图',tab_log:'日志',weather_title:'今日天气｜Ripley',refresh:'刷新',highlights:'今日重点',tasks:'今日养护任务',mark_patrol:'记录今日巡园',fertilizer:'本周施肥提醒',pruning:'本周修剪提醒',plant_archive:'植物档案',add_plant:'添加植物',garden_map:'花园地图',map_desc:'按区域查看植物。点击植物卡片可进入详情。',timeline:'成长时间轴',add_log:'添加日志',niania_report:'Niania 巡园报告',add_niania:'记录 Niania 今日巡视',current_temp:'当前温度',today_range:'今日范围',wind:'风速',rain:'降雨概率',loading_weather:'正在获取天气...',weather_failed:'天气获取失败。可稍后刷新。',all:'全部',water_need:'需水',health:'健康',light:'光照',care_records:'养护记录',last_watered:'上次浇水',last_fertilized:'上次施肥',last_pruned:'上次修剪',cat_safe:'猫友好',safe:'较安全',toxic:'需避开',caution:'谨慎',photos:'成长照片',record_water:'记录浇水',record_fert:'记录施肥',record_prune:'记录修剪',no_water:'今日通常不用浇',check_water:'今日建议检查并按需浇水',days_ago:'天前',not_recorded:'未记录',water:'浇水',fert:'施肥',prune:'修剪',saved_action:'已记录',patrol_saved:'已记录今日巡园。'},
  en:{export:'Export backup',tab_today:'Today',tab_plants:'Plants',tab_map:'Map',tab_log:'Log',weather_title:'Today\'s Weather | Ripley',refresh:'Refresh',highlights:'Today\'s Highlights',tasks:'Today\'s Care Tasks',mark_patrol:'Mark today\'s patrol',fertilizer:'Fertilising This Week',pruning:'Pruning This Week',plant_archive:'Plant Archive',add_plant:'Add Plant',garden_map:'Garden Map',map_desc:'View plants by area. Tap a plant card to open its details.',timeline:'Growth Timeline',add_log:'Add Log',niania_report:'Niania Patrol Report',add_niania:'Log Niania patrol',current_temp:'Current temperature',today_range:'Today\'s range',wind:'Wind speed',rain:'Rain chance',loading_weather:'Getting weather...',weather_failed:'Weather failed. Please refresh later.',all:'All',water_need:'Water need',health:'Health',light:'Light',care_records:'Care Records',last_watered:'Last watered',last_fertilized:'Last fertilised',last_pruned:'Last pruned',cat_safe:'Cat safety',safe:'Safer',toxic:'Keep away',caution:'Caution',photos:'Growth Photos',record_water:'Watered',record_fert:'Fertilised',record_prune:'Pruned',no_water:'Usually no watering today',check_water:'Check soil and water if needed',days_ago:'days ago',not_recorded:'Not recorded',water:'watering',fert:'fertilising',prune:'pruning',saved_action:'Recorded',patrol_saved:'Today\'s patrol saved.'}
};
const t = k => (I18N[lang]&&I18N[lang][k]) || I18N.zh[k] || k;
const dateFmt = () => new Intl.DateTimeFormat(lang==='zh'?'zh-CN':'en-AU',{year:'numeric',month:lang==='zh'?'2-digit':'short',day:'2-digit',weekday:'long'}).format(today).replace(/\//g,'-');
function applyLang(){
  document.documentElement.lang = lang==='zh'?'zh-CN':'en';
  document.getElementById('todayText').textContent = dateFmt();
  document.getElementById('langToggle').textContent = lang==='zh'?'EN':'中文';
  document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));
}

function seedPlants(){return [
{id:'jasmine-xiaomo',name:'小茉',species:'Jasmine',group:'前院',count:1,water:'高',light:'全日照～半日照',lastWatered:'2026-07-05',health:96,cat:'safe',notes:'已开花5朵，开花期保持微湿，花后再摘残花。',notesEn:'Blooming with 5 flowers. Keep evenly moist while flowering; deadhead after the flush.'},
{id:'star-jasmine-xiaoli',name:'小莉',species:'Star Jasmine',group:'前院',count:1,water:'中',light:'下午西晒',lastWatered:'2026-07-05',health:93,cat:'caution',notes:'下午西晒，连续晴天需提前检查土壤。',notesEn:'Gets afternoon sun. Check soil earlier during consecutive sunny days.'},
{id:'hydrangea',name:'绣球',species:'Hydrangea',group:'前院',count:2,water:'高',light:'半日照',lastWatered:'2026-07-05',health:92,cat:'toxic',notes:'新种后保持微湿，不要干透。',notesEn:'Newly planted. Keep slightly moist; do not let dry out completely.'},
{id:'passionfruit-yellow',name:'小黄',species:'Passionfruit',group:'前院',count:1,water:'高',light:'全日照',lastWatered:'2026-07-05',health:94,cat:'caution',notes:'已自主攀爬，大风后检查主藤和支撑。',notesEn:'Climbing well. After windy days, check the main vine and support.'},
{id:'passionfruit-red',name:'小红',species:'Passionfruit',group:'前院',count:1,water:'高',light:'全日照',lastWatered:'2026-07-05',health:92,cat:'caution',notes:'卷须还在寻找支撑，暂不强行缠网。',notesEn:'Tendrils are still finding support. Do not force them onto the net.'},
{id:'dragonfruit',name:'火龙果',species:'Dragon Fruit',group:'前院',count:1,water:'低',light:'全日照',lastWatered:'2026-06-29',health:90,cat:'safe',notes:'冬季控水，完全干再少量浇。',notesEn:'Keep dry in winter. Water lightly only when fully dry.'},
{id:'lawn',name:'新铺草皮',species:'New Turf',group:'草坪',count:1,water:'高',light:'全日照',lastWatered:'2026-07-04',health:88,cat:'safe',notes:'若已扎根可降低频率，局部发浅再补水。',notesEn:'Reduce watering once rooted; spot-water pale patches.'},
{id:'marguerite',name:'玛格丽特',species:'Marguerite Daisy',group:'前院',count:2,water:'中',light:'全日照',lastWatered:'2026-06-29',health:92,cat:'caution',notes:'检查残花，暂不重剪。',notesEn:'Check spent blooms; no hard pruning yet.'},
{id:'lavender',name:'薰衣草',species:'Lavender',group:'前院',count:2,water:'低',light:'全日照',lastWatered:'2026-06-29',health:86,cat:'caution',notes:'宁干勿湿，冬季不要频繁浇水。',notesEn:'Keep on the dry side; avoid frequent winter watering.'},
{id:'kalanchoe',name:'长寿花',species:'Kalanchoe',group:'前院',count:1,water:'低',light:'全日照～半日照',lastWatered:'2026-06-29',health:95,cat:'toxic',notes:'正在开花，花后剪花梗。',notesEn:'Blooming now. Remove flower stalks after flowering.'},
{id:'alyssum',name:'香雪球',species:'Sweet Alyssum',group:'前院',count:2,water:'中',light:'全日照',lastWatered:'2026-06-29',health:96,cat:'safe',notes:'盛花期，残花超过30%再轻剪。',notesEn:'Peak bloom. Lightly trim when spent flowers exceed about 30%.'},
{id:'blue-eyes',name:'Blue Eyes',species:'Evolvulus / Blue Eyes',group:'前院',count:8,water:'低',light:'全日照',lastWatered:'2026-06-25',health:88,cat:'caution',notes:'冬季偏干管理。',notesEn:'Keep slightly dry in winter.'},
{id:'silver-falls',name:'Silver Falls',species:'Dichondra Silver Falls',group:'前院',count:12,water:'低',light:'全日照～半日照',lastWatered:'2026-06-29',health:90,cat:'caution',notes:'新种前三个月不要修剪，观察弱苗新芽。',notesEn:'Do not prune in the first months; watch weaker plants for new growth.'},
{id:'silver-mist',name:'Silver Mist',species:'Helichrysum Silver Mist',group:'前院',count:1,water:'低',light:'全日照',lastWatered:'2026-06-25',health:91,cat:'caution',notes:'偏干管理，春季再施肥。',notesEn:'Keep on the dry side; fertilise in spring.'},
{id:'blob-sedum',name:'Speckled Blob Sedum',species:'Sedum',group:'前院',count:1,water:'低',light:'全日照',lastWatered:'2026-06-25',health:93,cat:'caution',notes:'多肉模式，完全干透再浇。',notesEn:'Succulent care: water only when fully dry.'},
{id:'gold-mound',name:'Gold Mound Sedum',species:'Sedum Gold Mound',group:'前院',count:2,water:'低',light:'全日照',lastWatered:'2026-06-25',health:93,cat:'caution',notes:'观赏为主，不建议食用。',notesEn:'Ornamental use; not recommended for eating.'},
{id:'rhoeo',name:'Rhoeo Dwarf',species:'Rhoeo / Tradescantia spathacea',group:'前院',count:1,water:'低',light:'全日照～半日照',lastWatered:'2026-06-25',health:90,cat:'toxic',notes:'耐旱，避免积水。',notesEn:'Drought tolerant; avoid waterlogging.'},
{id:'pink-gypsophila',name:'粉色满天星',species:'Gypsophila / Baby’s Breath',group:'前院',count:1,water:'中',light:'全日照',lastWatered:'2026-06-29',health:94,cat:'caution',notes:'盛花期，底部黄叶和花色变浅暂属正常。',notesEn:'Peak bloom. Lower yellow leaves and paler flowers appear normal for now.'},
{id:'aloe',name:'芦荟',species:'Aloe',group:'前院',count:3,water:'低',light:'半日照',lastWatered:'2026-06-25',health:78,cat:'toxic',notes:'继续停水观察黄化是否扩散。',notesEn:'Keep dry and monitor whether yellowing spreads.'},
{id:'large-cactus',name:'大仙人掌',species:'Cactus',group:'前院',count:1,water:'低',light:'全日照',lastWatered:'2026-06-25',health:92,cat:'caution',notes:'冬季2–3周不浇也可以。',notesEn:'Can go 2–3 weeks without water in winter.'},
{id:'echeveria',name:'拟石莲花/多肉',species:'Echeveria & Succulents',group:'前院',count:1,water:'低',light:'全日照',lastWatered:'2026-06-25',health:92,cat:'caution',notes:'完全干透再浇。',notesEn:'Water only when completely dry.'},
{id:'golden-cane-side',name:'黄金椰子',species:'Golden Cane Palm / Areca Palm',group:'侧院',count:3,water:'中',light:'约4小时西晒',lastWatered:'2026-07-01',health:91,cat:'safe',notes:'缓苗期，5–7天无雨且土干再浇透。',notesEn:'Establishing. Deep-water only if soil dries after 5–7 rainless days.'},
{id:'bird-paradise',name:'天堂鸟',species:'Bird of Paradise',group:'侧院',count:1,water:'中',light:'半日照',lastWatered:'2026-07-01',health:92,cat:'toxic',notes:'观察新叶舒展，轻微风裂正常。',notesEn:'Watch new leaves unfurl. Minor wind splits are normal.'},
{id:'cordyline',name:'粉叶朱蕉',species:'Cordyline fruticosa',group:'侧院',count:1,water:'中',light:'半日照～明亮散射光',lastWatered:'2026-07-01',health:95,cat:'toxic',notes:'色彩鲜艳，剪除完全黄掉的底叶即可。',notesEn:'Good colour. Remove only fully yellow lower leaves.'},
{id:'dragon-tree',name:'龙血树',species:'Dracaena marginata',group:'侧院',count:1,water:'低',light:'明亮散射光～半日照',lastWatered:'2026-07-06',health:95,cat:'toxic',notes:'新种下，首次浇透8–10L，之后5cm干再浇。',notesEn:'Newly planted. First deep watering 8–10 L; then water when top 5 cm dries.'},
{id:'variegated-side',name:'斑叶植物',species:'Variegated foliage plant',group:'侧院',count:3,water:'中',light:'半日照',lastWatered:'2026-07-01',health:92,cat:'caution',notes:'保持微湿，避免积水。',notesEn:'Keep slightly moist; avoid waterlogging.'},
{id:'areca-indoor',name:'室内散尾葵',species:'Areca Palm',group:'室内',count:1,water:'中',light:'明亮散射光',lastWatered:'2026-06-24',health:90,cat:'safe',notes:'深层干再缓慢浇透，倒掉托盘积水。',notesEn:'Water slowly and thoroughly only when deep soil is dry; empty saucer.'},
{id:'corkscrew-rush',name:'螺旋灯心草',species:'Juncus spiralis',group:'室内',count:1,water:'高',light:'明亮散射光',lastWatered:'2026-07-06',health:88,cat:'safe',notes:'保持持续湿润，剪除外围全黄老叶。',notesEn:'Keep consistently moist. Remove fully yellow outer leaves.'}
];}
function seedLogs(){return [
{date:'2026-07-06',title:'新增龙血树',titleEn:'Added Dragon Tree',text:'侧院新增龙血树，建议首次浇透8–10L。',textEn:'Added Dracaena to the side yard. First deep watering: 8–10 L.'},
{date:'2026-07-06',title:'主人名称更新',titleEn:'Owner name updated',text:'Garden Diary 改为 by Yue。',textEn:'Garden Diary updated to by Yue.'},
{date:'2026-07-05',title:'小黄小红大风观察',titleEn:'Wind check for passionfruit',text:'百香果经历大风，已临时挡风。',textEn:'Passionfruit vines experienced strong wind; temporary wind protection added.'},
{date:'2026-07-01',title:'小茉开花5朵',titleEn:'Xiao Mo opened 5 flowers',text:'小茉进入第一波盛花期。',textEn:'Jasmine entered its first flowering flush.'},
{date:'2026-07-01',title:'长寿花开花',titleEn:'Kalanchoe blooming',text:'长寿花正式进入花期。',textEn:'Kalanchoe has started flowering.'},
{date:'2026-06-29',title:'香雪球确认',titleEn:'Sweet Alyssum confirmed',text:'前院香雪球×2进入档案。',textEn:'Two Sweet Alyssum plants added to the front yard archive.'},
{date:'2026-06-29',title:'Silver Falls记录',titleEn:'Silver Falls recorded',text:'前院Silver Falls共12株。',textEn:'Twelve Silver Falls plants recorded in the front yard.'}
];}
function loadState(){const saved=localStorage.getItem(STORAGE_KEY); if(saved){try{return JSON.parse(saved)}catch(e){}} return {plants:seedPlants(),logs:seedLogs(),photos:{},niania:[{date:'2026-07-01',text:'Niania首次在草地尿尿，尿完直接离开。',textEn:'Niania peed on the lawn for the first time and walked away without burying it.'}]};}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function plantLabel(p){return lang==='zh' ? `${p.name}${p.count>1?' ×'+p.count:''}` : `${p.species||p.name}${p.count>1?' ×'+p.count:''}${p.name&&p.species?' / '+p.name:''}`}
function note(p){return lang==='zh' ? (p.notes||'') : (p.notesEn||p.notes||'')}
function groupLabel(g){if(lang==='zh') return g; return {'全部':'All','前院':'Front Yard','侧院':'Side Yard','室内':'Indoor','草坪':'Lawn'}[g]||g}
function waterLabel(w){if(lang==='zh') return w; return {'低':'Low','中':'Medium','高':'High'}[w]||w}
function renderAll(){applyLang();renderWeather();renderDashboard();renderFilters();renderPlants();renderMap();renderTimeline();renderNiania();}
async function renderWeather(){const box=document.getElementById('weatherBox'); box.innerHTML=t('loading_weather'); try{const url='https://api.open-meteo.com/v1/forecast?latitude=-27.68&longitude=152.78&current=temperature_2m,relative_humidity_2m,wind_speed_10m,weather_code&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=Australia%2FBrisbane'; const r=await fetch(url); const data=await r.json(); const c=data.current,d=data.daily; box.innerHTML=`<div class="weather-item"><div class="weather-temp">${Math.round(c.temperature_2m)}°C</div><div>${t('current_temp')}</div></div><div class="weather-item"><strong>${Math.round(d.temperature_2m_min[0])}–${Math.round(d.temperature_2m_max[0])}°C</strong><div>${t('today_range')}</div></div><div class="weather-item"><strong>${c.wind_speed_10m} km/h</strong><div>${t('wind')}</div></div><div class="weather-item"><strong>${d.precipitation_probability_max[0]}%</strong><div>${t('rain')}</div></div>`; }catch(e){box.innerHTML=`<div class="weather-item">${t('weather_failed')}</div>`}}
function plantTask(p){const d=daysSince(p.lastWatered); let due=false; if(p.water==='高'&&d>=2) due=true; if(p.water==='中'&&d>=4) due=true; if(p.water==='低'&&d>=9) due=true; return {p,d,due};}
function renderDashboard(){const tasks=state.plants.map(plantTask).filter(x=>x.due||['小茉','小莉','绣球','小黄','小红','龙血树','螺旋灯心草','室内散尾葵','芦荟','粉色满天星'].includes(x.p.name)); document.getElementById('taskList').innerHTML=tasks.slice(0,12).map(({p,d,due})=>`<div class="task"><strong>${plantLabel(p)}</strong><span class="muted">${t('last_watered')}：${p.lastWatered||t('not_recorded')}（${d>100?t('not_recorded'):d+' '+t('days_ago')}）</span><br>${due?'💧 '+t('check_water'):'✅ '+t('no_water')}｜${note(p)}</div>`).join(''); const h=lang==='zh'?['小茉持续开花，记录已更新为5朵。','龙血树已加入侧院档案，今天为新栽后重点观察。','百香果大风后继续检查主藤和支撑。','粉色满天星仍盛花，花色变浅暂属正常。','Niania 巡园栏目已保留。']:['Xiao Mo is still flowering; the record is updated to 5 blooms.','Dragon Tree has joined the side-yard archive and is a key observation after planting.','After strong wind, keep checking passionfruit vines and supports.','Pink Baby’s Breath is still in peak bloom; paler flowers look normal for now.','Niania Patrol is included.']; document.getElementById('highlights').innerHTML=h.map(x=>`<li>${x}</li>`).join(''); document.getElementById('fertilizerTips').innerHTML=lang==='zh'?'<p>当前为昆州冬季，绝大多数植物暂停施肥。百香果、绣球、Silver Falls、龙血树等建议等9月春季恢复生长后再开始少量追肥。</p>':'<p>It is winter in Queensland, so most plants should pause fertilising. Passionfruit, hydrangeas, Silver Falls and Dragon Tree can resume light feeding when growth restarts in spring around September.</p>'; document.getElementById('pruneTips').innerHTML=lang==='zh'?'<p>本周只做清理型修剪：通心草剪全黄老叶；满天星、香雪球只摘明显残花；小茉、小莉、百香果、龙血树暂不修剪。</p>':'<p>This week: only tidy-up pruning. Remove fully yellow Corkscrew Rush leaves; deadhead obvious spent flowers on Baby’s Breath and Alyssum. Do not prune jasmine, star jasmine, passionfruit or Dragon Tree yet.</p>';}
function groups(){return ['全部',...Array.from(new Set(state.plants.map(p=>p.group)))]}
function renderFilters(){document.getElementById('groupFilters').innerHTML=groups().map(g=>`<button class="filter ${g===selectedGroup?'active':''}" data-group="${g}">${groupLabel(g)}</button>`).join(''); document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{selectedGroup=b.dataset.group;renderFilters();renderPlants();});}
function renderPlants(){const list=selectedGroup==='全部'?state.plants:state.plants.filter(p=>p.group===selectedGroup); document.getElementById('plantCards').innerHTML=list.map(p=>`<article class="plant-card" data-id="${p.id}"><h3>${plantLabel(p)}</h3><p class="muted">${lang==='zh'?(p.species||''):(p.group?groupLabel(p.group):'')}</p><span class="badge">${groupLabel(p.group)}</span><span class="badge">${t('water_need')}：${waterLabel(p.water)}</span><span class="badge health">${t('health')} ${p.health||90}%</span><p>${note(p)}</p><div class="actions"><button data-action="water" data-id="${p.id}">${t('record_water')}</button><button data-action="fert" data-id="${p.id}">${t('record_fert')}</button><button data-action="prune" data-id="${p.id}">${t('record_prune')}</button></div></article>`).join(''); document.querySelectorAll('.plant-card').forEach(card=>{card.onclick=e=>{if(e.target.tagName==='BUTTON')return;openDetail(card.dataset.id)}}); document.querySelectorAll('[data-action]').forEach(btn=>btn.onclick=e=>{e.stopPropagation();recordAction(btn.dataset.id,btn.dataset.action)});}
function renderMap(){const by={}; state.plants.forEach(p=>(by[p.group]??=[]).push(p)); document.getElementById('gardenMap').innerHTML=Object.entries(by).map(([g,items])=>`<div class="map-zone"><h3>${groupLabel(g)}</h3>${items.map(p=>`<button class="map-pill" onclick="openDetail('${p.id}')">${plantLabel(p)}</button>`).join('')}</div>`).join('')}
function renderTimeline(){document.getElementById('timelineList').innerHTML=state.logs.sort((a,b)=>b.date.localeCompare(a.date)).map(l=>`<div class="log"><strong>${l.date}｜${lang==='zh'?(l.title||l.titleEn):(l.titleEn||l.title)}</strong><p>${lang==='zh'?(l.text||l.textEn):(l.textEn||l.text||'')}</p></div>`).join('')}
function renderNiania(){const intro=lang==='zh'?'今日巡园重点：检查百香果支撑、确认没有偷啃龙血树和粉叶朱蕉、监督园长浇水。':'Today’s patrol focus: check passionfruit supports, make sure Dragon Tree and Cordyline are not nibbled, and supervise watering.'; document.getElementById('nianiaReport').innerHTML='<p>'+intro+'</p>'+state.niania.slice().reverse().map(l=>`<div class="log"><strong>${l.date}</strong><p>${lang==='zh'?(l.text||l.textEn):(l.textEn||l.text)}</p></div>`).join('')}
function recordAction(id,action){const p=state.plants.find(x=>x.id===id); const map={water:t('water'),fert:t('fert'),prune:t('prune')}; if(action==='water')p.lastWatered=iso(today); if(action==='fert')p.lastFertilized=iso(today); if(action==='prune')p.lastPruned=iso(today); state.logs.push({date:iso(today),title:`${p.name}：${map[action]}`,titleEn:`${p.species||p.name}: ${map[action]}`,text:`${t('saved_action')}${map[action]}。`,textEn:`${t('saved_action')} ${map[action]}.`}); save();renderAll();}
window.openDetail=function(id){const p=state.plants.find(x=>x.id===id); const photos=state.photos[id]||[]; document.getElementById('plantDetail').innerHTML=`<h2>${plantLabel(p)}</h2><p class="muted">${p.species||''}</p><span class="badge">${groupLabel(p.group)}</span><span class="badge">${t('water_need')}：${waterLabel(p.water)}</span><span class="badge">${t('light')}：${p.light||t('not_recorded')}</span><span class="badge">${t('cat_safe')}：${p.cat==='safe'?t('safe'):p.cat==='toxic'?t('toxic'):t('caution')}</span><h3>${t('care_records')}</h3><p>${t('last_watered')}：${p.lastWatered||t('not_recorded')}</p><p>${t('last_fertilized')}：${p.lastFertilized||t('not_recorded')}</p><p>${t('last_pruned')}：${p.lastPruned||t('not_recorded')}</p><p>${note(p)}</p><div class="actions"><button onclick="recordAction('${p.id}','water')">${t('record_water')}</button><button onclick="recordAction('${p.id}','fert')">${t('record_fert')}</button><button onclick="recordAction('${p.id}','prune')">${t('record_prune')}</button></div><h3>${t('photos')}</h3><input type="file" accept="image/*" id="photoInput"><div class="photo-preview">${photos.map(src=>`<img src="${src}">`).join('')}</div>`; document.getElementById('detailDialog').showModal(); document.getElementById('photoInput').onchange=e=>{const file=e.target.files[0]; if(!file)return; const reader=new FileReader(); reader.onload=()=>{(state.photos[id]??=[]).push(reader.result); state.logs.push({date:iso(today),title:`${p.name}新增照片`,titleEn:`New photo for ${p.species||p.name}`,text:'已添加成长照片。',textEn:'Growth photo added.'}); save();openDetail(id);}; reader.readAsDataURL(file);};}
document.getElementById('closeDetail').onclick=()=>document.getElementById('detailDialog').close();
document.getElementById('langToggle').onclick=()=>{lang=lang==='zh'?'en':'zh';localStorage.setItem(LANG_KEY,lang);renderAll();};
document.getElementById('addPlantBtn').onclick=()=>{document.getElementById('plantForm').reset();document.getElementById('plantId').value='';document.getElementById('plantDialog').showModal();}
document.getElementById('plantForm').onsubmit=e=>{e.preventDefault(); const id=document.getElementById('plantId').value||('plant-'+Date.now()); const p={id:id,name:document.getElementById('plantName').value,species:document.getElementById('plantSpecies').value,group:document.getElementById('plantGroup').value,count:+document.getElementById('plantCount').value||1,water:document.getElementById('plantWater').value,light:document.getElementById('plantLight').value,notes:document.getElementById('plantNotes').value,lastWatered:null,health:90,cat:'caution'}; state.plants.push(p); state.logs.push({date:iso(today),title:`新增植物：${p.name}`,titleEn:`New plant: ${p.species||p.name}`,text:`已加入${p.group}。`,textEn:`Added to ${groupLabel(p.group)}.`}); save();document.getElementById('plantDialog').close();renderAll();}
document.getElementById('addLogBtn').onclick=()=>document.getElementById('logDialog').showModal();
document.getElementById('logForm').onsubmit=e=>{e.preventDefault();state.logs.push({date:iso(today),title:document.getElementById('logTitle').value,text:document.getElementById('logText').value});save();document.getElementById('logDialog').close();renderTimeline();}
document.getElementById('addNianiaLog').onclick=()=>{state.niania.push({date:iso(today),text:'Niania 今日完成巡园。',textEn:'Niania completed today’s patrol.'});save();renderNiania();}
document.getElementById('markDiary').onclick=()=>{state.logs.push({date:iso(today),title:'今日巡园完成',titleEn:'Today’s patrol completed',text:'已查看天气、浇水、施肥和修剪提醒。',textEn:'Checked weather, watering, fertilising and pruning reminders.'});save();renderTimeline();alert(t('patrol_saved'))}
document.getElementById('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='garden-diary-backup-'+iso(today)+'.json'; a.click();}
document.getElementById('refreshWeather').onclick=renderWeather;
function switchView(view){document.querySelectorAll('.view').forEach(s=>s.classList.toggle('active',s.id===view));document.querySelectorAll('.tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>switchView(tab.dataset.view)));
renderAll();
